# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6711f6c57a8ef1850ccb902923b8190979e59e2142fc892ffc4e85101070efb239edfebaafcd46d4709601f90574516afd53d89e8ac87066cfc25deb8e77c6

test:
  secret_key_base: 123313fcde30f241c6ce18a375893fac59092d6b301ca3d6a829bcafab968b7cb82d21560d68420a256adc326b41d81a3d342aea73e9777fda33edd39cce6c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
